[package]
name = "minesweeper"
version = "0.1.0"
authors = ["Wesley Hendriksen <wesleyhendriksen@hotmail.com>"]
edition = "2018"

[dependencies]
piston = "0.40.0"
pistoncore-glutin_window = "0.52.0"
piston2d-graphics = "0.30.0"
piston2d-opengl_graphics = "0.59.0"
rand = "0.6.5"
